### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by TPepperoni666** [Oganoth/Framework-Hub-PY#1]
Fan Control with different power profiles
Driver version detector and a way to flag that there's a driver update
Screen Control. I.e refresh rate
Free adjustment of TDP for different profiles
Switch profiles based on charger being connected or disconnected. (If charger connected it could switch from silent to balanced / performance)
Disable dGPU on battery and enables when plugged in
Maybe a way to control the macro pad and LED Matrix in app
A way to control the battery charge limit (Not sure if it is even do able in windows with FW but would love it.)
Extra hotkeys for changing settings
A smaller version of the UI that acts as a pop for quick acces too all settings.

As you can see, these are all functions in g helper that I would love to see incorporated in some way to this some how.

**Comment by Oganoth** [comment]
There are a lot of good ideas here !

I already worked on a way to integrate fan control but since it rely on activating unsecured settings in windows like test drivers,... I don't like so I'm waiting for a Bios update to enable more control natively. 😁

I'll look into the others ideas tomorrow if I have time to commit some updates stay tuned !

**Comment by TPepperoni666** [comment]
Yeah I wasn't sure what is or ins't included already seeing as I dont have one yet. Looking forward to seeing this progress!

**Comment by Oganoth** [comment]
look the new version :)

**Comment by TPepperoni666** [comment]
WOW JUST WOW! This is excellent!

**Comment by Oganoth** [comment]
And there is still more to come 😁

**Comment by TPepperoni666** [comment]
Another QOL suggestion would be to have the window be forced to the front, so that another app can't 'hide' it?
