### ISSUE TITLE
Commit 0cab360 introduced a .gitignore that included three icon paths, app won't start

### ISSUE THREAD

**Issue by RikPi** [Oganoth/Framework-Hub-PY#2]
Hi,
First of all, great project and thank you for providing this software open source!

### Problem
With the latest commit (0cab360), the app won't start because of a FileNotFoundError (line 256 of mini.py). This happens because the icons "tray_icon.png", "error_icon.png" and "info_icon.png" are not found. In that commit, the .gitignore listed them as ignored, but the assets folder includes a .ico version of "tray_icon", I imagine that you were migrating from .png to .ico

### Proposed solution
Add "error_icon.ico" and "info_icon.ico" to the assets folder and change lines 244:246 of mini.py accordingly to have the .ico extension

Thank you and let me know if I can help further :)
Riccardo

**Comment by Oganoth** [comment]
Fixed
